#!/usr/bin/env bash
DIR="$HOME"/.gdrive-downloader
REPO="gdrive-downloader"

CURRENT_SHELL="${SHELL##*/}"
case "$CURRENT_SHELL" in
    'bash') SHELL_FILE="$(ls "$HOME"/.bashrc)" ;;
    'zsh') SHELL_FILE="$(ls "$HOME"/.zshrc)" ;;
    *) echo "Not a supported shell" && exit 1 ;;
esac

if ! type -p gdl > /dev/null 2>&1; then
    printf 'gdrive-downloader not installed\n'
    printf "Fetching latest sha..\n"
    LATEST_CURRENT_SHA="$(hash="$(curl --compressed -s https://github.com/Akianonymus/"$REPO"/commits/master.atom | grep "Commit\\/")" && read -r firstline <<< "$hash" && regex="(/.*<)" && [[ $firstline =~ $regex ]] && echo "${BASH_REMATCH[1]:1:-1}")"
    printf "\033[1A\033[2K" && printf "Latest sha fetched"
    mkdir -p "$DIR"
    wget -q --show-progress --progress=bar:force https://raw.githubusercontent.com/Akianonymus/"$REPO"/master/gdl -O "$DIR"/gdl
    echo "curl -s https://raw.githubusercontent.com/Akianonymus/""$REPO""/master/update_gdl | bash" > "$DIR"/update_gdl
    chmod +x "$DIR"/gdl "$DIR"/update_gdl
    PATH="$DIR"/:$PATH
    export PATH
    printf "\n%s\n" "PATH=""$DIR""/:$PATH" >> "$SHELL_FILE"
    echo "$LATEST_CURRENT_SHA" > "$DIR"/gdl.sha
    echo "Installed Successfully, Command name: gdl"
    echo "Reload your shell by"
    echo "source $SHELL_FILE"
    echo "To update the script in future, just run update_gdl"
else
    echo "gdrive-downloader already installed"
    echo "Command name: gdl"
    if type -a update_gdl > /dev/null 2>&1; then
        echo "To update the script, just run update_gdl"
    else
        echo "curl -s https://raw.githubusercontent.com/Akianonymus/""$REPO""/master/update_gdl | bash" > "$(dirname "$(type -a gdl)")"/update_gdl || exit 1
        echo "To update the script, just run update_gdl"
    fi
    echo "Installed Path: $(type -p gdl)"
fi
