#!/usr/bin/env bash
DIR="$HOME"/.gdrive-downloader
REPO="gdrive-downloader"

# If internet connection is not available.
# Probably the fastest way, takes about 1 - 2 KB of data, don't check for more than 10 secs.
# https://unix.stackexchange.com/a/18711 to timeout without any external program.
checkInternet() {
    if [[ -t 1 ]]; then
        CHECK_INTERNET="$(sh -ic 'exec 3>&1 2>/dev/null; { curl --compressed -Is google.com 1>&3; kill 0; } | { sleep 10; kill 0; }' || :)"
    else
        CHECK_INTERNET="$(curl --compressed -Is google.com -m 10)"
    fi
    if [[ -z $CHECK_INTERNET ]]; then
        printf "[ Error: Internet connection not available ]" "="
        exit 1
    fi
}

checkInternet

if [[ -d "$DIR" ]]; then
    if ! ls -A "$DIR" > /dev/null 2>&1; then
        printf 'gdrive-downloader not installed\n\n'
        exit 1
    fi
else
    printf 'gdrive-downloader not installed\n\n'
    exit 1
fi

LATEST_CURRENT_SHA="$(hash="$(curl --compressed -s https://github.com/Akianonymus/"$REPO"/commits/master.atom | grep "Commit\\/")" && read -r firstline <<< "$hash" && regex="(/.*<)" && [[ $firstline =~ $regex ]] && echo "${BASH_REMATCH[1]:1:-1}")"
if [[ -z "$LATEST_CURRENT_SHA" ]]; then
    printf 'Cannot fetch remote version.\n\n'
    exit 1
fi

LATEST_INSTALLED_SHA="$(< "$DIR"/gdl.sha)"
if [[ -z "$LATEST_INSTALLED_SHA" ]]; then
    printf 'Cannot determine local version\n\n'
    exit 1
fi

if [[ "$LATEST_CURRENT_SHA" == "$LATEST_INSTALLED_SHA" ]]; then
    printf 'Latest gdrive-downloader already installed\n\n'
else
    echo 'Updating...'
    wget -q --show-progress --progress=bar:force https://github.com/Akianonymus/"$REPO"/raw/master/gdl -O "$DIR"/gdl
    echo "$LATEST_CURRENT_SHA" > "$DIR"/gdl.sha
    printf '\033[1A  '
    printf 'Successfully Updated.\n\n'
fi
